// Re-exported ui-service contract types (zero-duplication, DR-0018 §2).
// Source of truth: agent-server/src/domain/ui-service/types.ts. We import the
// BUILT declarations so the frontend shares one definition and cannot drift.
// All re-exports are type-only → fully erased at build, no runtime coupling to
// agent-server (the frontend never bundles backend code).

export type {
  // Result envelope
  Result,
  Ok,
  Err,
  // Scope / op unions
  QueryScope,
  MutateOp,
  // Subscribe
  SubscribeFilter,
  UiEvent,
  ExecutionsLogParams,
  // Query params
  SessionsListParams,
  SessionsTranscriptParams,
  ThreadsListParams,
  ThreadsGetParams,
  TasksListParams,
  SchedulesListParams,
  ExecutionsListParams,
  ExecutionsGetParams,
  MemoryTreeParams,
  MemoryFileParams,
  ApprovalsListParams,
  CostSummaryParams,
  ConfigGetParams,
  MachinesListParams,
  SkillsListParams,
  // Mutate args
  ProjectCreateArgs,
  SessionsCreateArgs,
  SessionsSendArgs,
  SessionsSetProfileArgs,
  ThreadsCancelArgs,
  ExecutionsCancelArgs,
  ScheduleActionArgs,
  ScheduleAddArgs,
  TaskActionArgs,
  TaskCompleteArgs,
  TaskBlockArgs,
  BudgetValue,
  ProfilesValue,
  ConfigSetArgs,
  ApprovalsApproveArgs,
  ApprovalsRejectArgs,
  ApprovalsRequestArgs,
  SessionsAnswerQuestionArgs,
  SessionsRespondPlanArgs,
  SessionsPendingInteractionParams,
  SessionsPendingInteraction,
  // Output DTOs
  ProjectConduitInfo,
  SessionInfo,
  SessionTranscript,
  TranscriptTurn,
  TranscriptMessage,
  ThreadInfo,
  ThreadDetail,
  ThreadStepDetail,
  ThreadAgentFlow,
  ThreadDispatchInfo,
  ThreadChildNode,
  ThreadArtifactRefs,
  TaskInfo,
  TaskVerificationParams,
  TaskVerificationInfo,
  TaskDoneWhenEvidence,
  TaskDispatchRecord,
  ScheduleInfo,
  ExecutionInfo,
  ExecutionDetailInfo,
  ConfigSnapshot,
  ConfigBudget,
  ConfigProfiles,
  ConfigProfileEntry,
  ConfigMachine,
  ConfigMcp,
  ConfigThreadTemplates,
  ConfigEnvEntry,
  MemoryTree,
  MemoryFileEntry,
  MemoryDirEntry,
  MemoryFile,
  MemoryLineDiff,
  MemoryBlameLine,
  ProjectCreateReturn,
  SessionsCreateReturn,
  SessionsSendReturn,
  SessionsSetProfileReturn,
  ThreadsCancelReturn,
  ExecutionsCancelReturn,
  ConfigSetReturn,
  ApprovalStatus,
  ApprovalInfo,
  ApprovalMutateReturn,
  ApprovalsRequestReturn,
  MachineInfo,
  SkillGroup,
  ThreadTemplateEntry,
  ThreadTemplatesGetParams,
  SystemDaemonStatusParams,
  SystemDaemonStatus,
  DaemonProcessInfo,
  SystemRestartArgs,
  SystemRestartReturn,
  // Mapped contract
  QueryParamMap,
  QueryReturnMap,
  MutateArgsMap,
  MutateReturnMap,
  QueryParams,
  QueryReturn,
  MutateArgs,
  MutateReturn,
} from '@cortex-agent/server/dist/domain/ui-service/types.js';

// CostSummary is the cost.summary return DTO; it is defined in the costs domain
// and pulled into the ui-service contract there, not re-exported by the barrel.
export type { CostSummary } from '@cortex-agent/server/dist/domain/costs/cost-tracker.js';
