// input:  built ui-service declarations including DEBUG and pending transcript details
// output: zero-duplication type-only client contract re-exports
// pos:    shared server→desktop/mobile compile-time DTO boundary; no frontend runtime coupling
// >>> If I am updated, update my header comment and the parent folder's CORTEX.md <<<

export type {
  // Result envelope
  Result,
  Ok,
  Err,
  // Scope / op unions
  QueryScope,
  MutateOp,
  // Subscribe
  SubscribeFilter,
  UiEvent,
  ExecutionsLogParams,
  // Query params
  SessionsListParams,
  SessionsTranscriptParams,
  ThreadsListParams,
  ThreadsGetParams,
  TasksListParams,
  SchedulesListParams,
  ExecutionsListParams,
  ExecutionsGetParams,
  MemoryTreeParams,
  MemoryFileParams,
  ApprovalsListParams,
  IssuesListParams,
  CostSummaryParams,
  ConfigGetParams,
  MachinesListParams,
  SkillsListParams,
  // Mutate args
  ProjectCreateArgs,
  SessionsCreateArgs,
  SessionsSendArgs,
  SessionsSetProfileArgs,
  ThreadsCancelArgs,
  ExecutionsCancelArgs,
  ScheduleActionArgs,
  ScheduleAddArgs,
  TaskActionArgs,
  TaskCompleteArgs,
  TaskBlockArgs,
  BudgetValue,
  ProfilesValue,
  ConfigSetArgs,
  ApprovalsApproveArgs,
  ApprovalsRejectArgs,
  ApprovalsRequestArgs,
  IssueActionArgs,
  SessionsAnswerQuestionArgs,
  SessionsRespondPlanArgs,
  SessionsPendingInteractionParams,
  SessionsPendingInteraction,
  SessionsInteractionMutateReturn,
  // Interaction entity (web-interactions-redesign)
  InteractionKind,
  InteractionStatus,
  InteractionQuestion,
  TranscriptInteractionDetail,
  TranscriptDebugDetails,
  // Output DTOs
  ProjectConduitInfo,
  SessionInfo,
  SessionTranscript,
  PendingTranscriptUserMessage,
  TranscriptTurn,
  TranscriptMessage,
  ThreadInfo,
  ThreadDetail,
  ThreadStepDetail,
  ThreadAgentFlow,
  ThreadDispatchInfo,
  ThreadChildNode,
  ThreadArtifactRefs,
  TaskInfo,
  TaskVerificationParams,
  TaskVerificationInfo,
  TaskDoneWhenEvidence,
  TaskDispatchRecord,
  ScheduleInfo,
  ExecutionInfo,
  ExecutionDetailInfo,
  ConfigSnapshot,
  ConfigBudget,
  ConfigProfiles,
  ConfigProfileEntry,
  ConfigMachine,
  ConfigMcp,
  ConfigThreadTemplates,
  ConfigEnvEntry,
  MemoryTree,
  MemoryFileEntry,
  MemoryDirEntry,
  MemoryFile,
  MemoryLineDiff,
  MemoryBlameLine,
  ProjectCreateReturn,
  SessionsCreateReturn,
  SessionsSendReturn,
  SessionsSetProfileReturn,
  ThreadsCancelReturn,
  ExecutionsCancelReturn,
  ConfigSetReturn,
  ApprovalStatus,
  ApprovalInfo,
  ApprovalMutateReturn,
  ApprovalsRequestReturn,
  IssueInfo,
  IssuesDeleteReturn,
  IssuesHandleReturn,
  MachineInfo,
  SkillGroup,
  ThreadTemplateEntry,
  ThreadTemplatesGetParams,
  SystemDaemonStatusParams,
  SystemDaemonStatus,
  DaemonProcessInfo,
  SystemRestartArgs,
  SystemRestartReturn,
  // Mapped contract
  QueryParamMap,
  QueryReturnMap,
  MutateArgsMap,
  MutateReturnMap,
  QueryParams,
  QueryReturn,
  MutateArgs,
  MutateReturn,
} from '@cortex-agent/server/dist/domain/ui-service/types.js';

// CostSummary is the cost.summary return DTO; it is defined in the costs domain
// and pulled into the ui-service contract there, not re-exported by the barrel.
export type { CostSummary } from '@cortex-agent/server/dist/domain/costs/cost-tracker.js';
