// input:  built agent-server ui-service input schemas
// output: runtime/type schemas including session compact/rate limits
// pos:    Shared browser/server input validation boundary
// >>> If I am updated, update my header comment and the parent folder's CORTEX.md <<<

export {
  projectsListInput,
  projectsCreateInput,
  sessionsListInput,
  sessionsTranscriptInput,
  sessionsCreateInput,
  sessionsSendInput,
  sessionsCompactInput,
  sessionsSetProfileInput,
  threadsListInput,
  threadsGetInput,
  tasksListInput,
  taskVerificationInput,
  schedulesListInput,
  executionsListInput,
  executionsGetInput,
  memoryTreeInput,
  memoryFileInput,
  approvalsListInput,
  approvalsApproveInput,
  approvalsRejectInput,
  approvalsRequestInput,
  issuesListInput,
  issueActionInput,
  costSummaryInput,
  threadsCancelInput,
  executionsCancelInput,
  scheduleActionInput,
  scheduleAddInput,
  taskActionInput,
  taskCompleteInput,
  taskBlockInput,
  executionsLogInput,
  configGetInput,
  configSetInput,
  hooksListInput,
  hooksCreateInput,
  hooksUpdateInput,
  hooksSetEnabledInput,
  hooksRemoveInput,
  hooksTestInput,
  machinesListInput,
  skillsListInput,
  threadTemplatesGetInput,
  systemDaemonStatusInput,
  systemRateLimitStatusInput,
  systemRestartInput,
  sessionsAnswerQuestionInput,
  sessionsRespondPlanInput,
  sessionsPendingInteractionInput,
  queryInputSchemas,
  mutateInputSchemas,
} from '@cortex-agent/server/dist/domain/ui-service/input-schemas.js';
