// input:  ThemeProvider, AccentPicker, appearance utilities
// output: Public theme controls and preference API
// pos:    Theme package barrel
// >>> If I am updated, update my header comment and CORTEX.md <<<

export { AccentPicker, type AccentPickerCopy } from './AccentPicker';
export {
  ThemeProvider,
  useAccentHue,
  useSetAccentHue,
  useAccentIntensity,
  useSetAccentIntensity,
  useSurfaceTone,
  useSetSurfaceTone,
  useMotionMode,
  useSetMotionMode,
  useTheme,
  useSetTheme,
  useToggleTheme,
} from './ThemeProvider';
export {
  applyAccentHue,
  applyAccentIntensity,
  applyMotionMode,
  applySurfaceTone,
  applyTheme,
  parseStoredAccentHue,
  parseStoredAccentIntensity,
  parseStoredMotionMode,
  parseStoredSurfaceTone,
  readStoredAccentHue,
  readStoredAccentIntensity,
  readStoredMotionMode,
  readStoredSurfaceTone,
  readStoredTheme,
  storeAccentHue,
  storeAccentIntensity,
  storeMotionMode,
  storeSurfaceTone,
  storeTheme,
  resolveInitialTheme,
  ACCENT_HUE_STORAGE_KEY,
  ACCENT_INTENSITY_STORAGE_KEY,
  MOTION_STORAGE_KEY,
  SURFACE_TONE_STORAGE_KEY,
  DEFAULT_ACCENT_HUE,
  DEFAULT_ACCENT_INTENSITY,
  DEFAULT_MOTION_MODE,
  DEFAULT_SURFACE_TONE,
  THEME_STORAGE_KEY,
  DEFAULT_THEME,
  type AccentHue,
  type AccentIntensity,
  type MotionMode,
  type SurfaceTone,
  type Theme,
} from './theme';
